# Project
sonar.projectKey=akhyarrasyid_project-tracker
sonar.organization=akhyarrasyid
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8

# Source code
sonar.sources=backend/app,frontend/src

# Tests
sonar.tests=backend/tests,frontend/src
sonar.test.inclusions=backend/tests/**/*.py,frontend/**/*.test.tsx,frontend/**/*.test.ts
sonar.test.exclusions=**/*.pyc

# Ignore generated / dependency files
sonar.exclusions=\
  **/node_modules/**,\
  **/.venv/**,\
  **/__pycache__/**,\
  **/dist/**,\
  **/build/**,\
  frontend/src/**/*.test.tsx,\
  frontend/src/**/*.test.ts,\
  backend/app/db/seeds/**

# Coverage reports
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

