# Project
sonar.projectKey=akhyarrasyid_project-tracker
sonar.organization=akhyarrasyid
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8

# Source code
sonar.sources=backend,frontend

# Ignore generated / dependency files
sonar.exclusions=\
**/node_modules/**,\
**/.venv/**,\
**/__pycache__/**,\
**/dist/**,\
**/build/**
